import { Cycle } from '../types';

export type RootStackParamList = {
  Login: undefined;
  SignUp: undefined;
  EmailOtp: { verifyUrl: string; email: string; fullName?: string; isForgotPassword?: boolean };
  ForgotPassword: { email?: string } | undefined;
  ResetPassword: { resetUrl?: string; tempToken?: string; email?: string } | undefined;
  Choice: undefined;
  Home: undefined;
  BookingDetail: { cycle?: Cycle; cycleId?: string };
  OngoingRentals: undefined;
  CycleOwner: { refresh?: number } | undefined;
  Landing: undefined;
  Listing: { editCycleId?: string; cycleId?: any; cycle?: Cycle } | undefined;
  Notifications: undefined;
  OtpVerification: { bookingId: string; actionType?: string };
  Return: { bookingId: string };
  Chat: {
    id?: string;
    conversationId?: string;
    bookingId: string;
    otherUserId: string;
    otherUserName: string;
    otherUserAvatar?: string;
    isOwner?: boolean;
    myRole?: 'renter' | 'owner' | string;
    cycleName?: string;
    cycleImage?: string;
    location?: string;
    rentalStatus?: string;
    startTime?: string;
    endTime?: string;
    totalAmount?: number | string;
  };
  CallModal: {
    id?: string | number;
    call_id?: string | number;
    targetUserId?: string;
    targetUserName?: string;
    targetUserAvatar?: string;
    bookingId?: string;
    conversationId?: string;
    callData?: any;
    isIncoming?: boolean;
  };
  Profile: undefined;
  BookingHistory: undefined;
  Wallet: undefined;
  AdminDashboard: undefined;
  AdminAllCycles: undefined;
  AdminAllUsers: undefined;
  AdminActiveRides: undefined;
  AdminCycleVerifications: undefined;
  AdminReports: undefined;
  CycleVerification: { cycleId: string; cycle?: Cycle };
  OwnerDetails: { ownerId?: string; owner?: any };
};
